### ISSUE TITLE
Search by type

### ISSUE THREAD

**Issue by jmbw88** [Dylan-Thomson/tinfur#1]
As a user I want to be able to search by animal type

-[] Build a field that allows a user to create a text search value.
-[] On Submit, capture that search value. 
-[] Add captured search value to API query.
-[] Create display cards for animals based on that qualifier in API return.

**Comment by slacker2222** [comment]
Also would like to see Google Map access to access location of animal.  Does this occur after animal is chosen, or should there be a radius first
